Remove old branches
openshift-knative/hack pull request #90
Opened 2023-11-10 14:32 UTC by skonto

- Remove branches < 1.9 and variants < 4.11

2023-11-10 14:34 UTC, skonto commented
Should I move Eventing to 1.14 instead of 1.13?

2023-11-13 06:09 UTC, ReToCode approved these changes
/lgtm
/approve
/hold I think it's fine with 4.14, but up to @pierDipi to confirm

2023-11-14 08:01 UTC, skonto commented
@ReToCode @pierDipi gentle ping.

2023-11-14 08:02 UTC, ReToCode requested changes

2023-11-14 08:02 UTC, ReToCode commented on config/eventing-hyperfoil-benchmark.yaml
> +        - 4.14
version:

2023-11-14 08:03 UTC, ReToCode commented
Just to not miss it, are we doing the eventing bump to 4.14 in a separate PR?

2023-11-14 09:31 UTC, pierDipi reviewed
This will need to be implemented in the controller logic https://github.com/openshift-knative/hack/issues/48, so we would need to "remove the YAML files before generating"

2023-11-14 13:29 UTC, skonto commented
@pierDipi in order to complete this for each repo:

- controller needs to read the repo config and marks what needs to be deleted based on the branches not in config
- removes old yaml files
- proceeds with the new files
If that is so I could try implement it.

2023-11-14 14:04 UTC, skonto commented on config/eventing-hyperfoil-benchmark.yaml
> +        - 4.14
yeah needs rebase

2023-11-15 09:30 UTC, pierDipi commented
> @pierDipi just to verify, in order to complete this task for each repo:
> 
> 1. controller needs to read the repo config and mark what needs to be deleted based on the branches not in config
> 2. removes old yaml files
> * proceeds with the new files generation
> 
> If that is so I could try implement it, so we can have proper clean up.

yes!

2023-11-15 09:32 UTC, pierDipi commented
We can also simply "remove all the YAML files in the repository config directory using a regex like `*.yaml`", so combining (1) and (2) without "marking what needs to be deleted" as it's equivalent when combined with (3)

2023-11-15 13:13 UTC, skonto commented
I will make it a bit more complex keeping the exclude stuff instead of removing everything. I will have a PR shortly.

2023-11-15 15:16 UTC, skonto commented on pkg/prowgen/prowgen_test.go
> +				"release-v3.1": {},
Ideally we could only use the branch name only and pass an array instead of a map, but not that important I would say.

2023-11-15 15:18 UTC, skonto commented on pkg/prowgen/prowgen.go
> +	for _, branchPrefix := range getOldBranchCandidatePrefixes(inConfig.Config.Branches, "release-v") {
S-O not covered yet but we could as soon as we decide what branches we want to keep. For now leaving it untouched although if we remove the related midstream branches the corresponding S-O ones should follow.

2023-11-16 13:24 UTC, skonto commented
@ReToCode @mgencur @pierDipi pls review.

2023-11-20 07:15 UTC, ReToCode reviewed
Hm, can you elaborate why we need that special handling in `getOldBranchCandidatePrefixes`? We do not have semver in the release branches anywhere, right? (we only have a xx.xx pattern) I don't seem to get why we need this.

Also the tests you added are a bit confusing, looking at the `branches` and the `want` I cannot really make sense of it. Why do we have totally different versions in `want`?

2023-11-20 08:33 UTC, skonto commented
> Hm, can you elaborate why we need that special handling in getOldBranchCandidatePrefixes?

I keep the option of skipping branches as the code was before by respecting: `deleteConfigsIfNeeded`. I don't delete evrything.

> Also the tests you added are a bit confusing, looking at the branches and the want I cannot really make sense of it. Why do we have totally different versions in want?

It is a test that makes sure that only branches with pattern release-vX.Y are parsed and if let's say you have the lower version release-v2.2 anything before v2.2 is removed unless there is some condition that want us to keep the branch.

2023-11-20 12:17 UTC, ReToCode commented
Thanks for explaining, I think I get your thoughts now. But I still feel is a bit complex for what we do. Wouldn't something similar to to [Pierangelos proposal](https://github.com/openshift-knative/hack/pull/90#issuecomment-1812099378) and respecting `ToRegexp(r.IgnoreConfigs.Matches)`  work, or am I missing something? So basically like:

- Loop over all existing folders+files and remove everything that is not not in the `IgnoreConfigs`
- Regenerate the config for everything that is still defined in the `config` files

So we should end up with the same but do not need to parse and compare versions.

2023-11-21 16:47 UTC, skonto commented
closing in favor of #93

2023-11-21 16:47 UTC, closed without merging